import React, { ReactElement } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import TranslationProvider from "@/components/provider/TranslatorProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blueberry App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactElement<{ lang: string }>;
  params: { lang: string }; 
}>) {
  const lang = params.lang || "en"; 

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranslationProvider lang={lang}>
          <Layout language={lang}>
            {React.cloneElement(children, { lang })}
          </Layout>
        </TranslationProvider>
      </body>
    </html>
  );
}
